
fourmis: fourmis.c
	gcc $< -lpthread -lncurses -o fourmis.o

#####################################
#####################################
#####################################

clean:
	rm -f *.o

restart: clean fourmis

